import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Container from "./components/shared/container";
import Footer from "./components/shared/footer";
import Providers from "./components/shared/providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Crosshair DB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='dark'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased flex flex-col min-h-screen`}
        suppressHydrationWarning={true}
      >
        <Container>
          <Providers>{children}</Providers>
        </Container>
        <Footer />
      </body>
    </html>
  );
}
